#!/bin/bash
#PBS -P vb2
#PBS -q express
#PBS -l walltime=02:00:00
#PBS -l mem=32GB
#PBS -l ncpus=16
#PBS -l wd

module load python3

IN=$INFILE		# argument passed in from the master script
OUT=$OUTFILE		# argument passed in from the master script

# use Porechop to trim adapters and split reads with an adapter in the middle
/short/xf1/src_big/Porechop/porechop-runner.py -i $IN -o $OUT \
 --threads 16 --discard_middle --verbosity 2

